const path=require('path');const express=require('express'),http=require('http'),cors=require('cors'),{Server}=require('socket.io'),players=require('./data/players.json');
const app=express();app.use(cors());app.use(express.json());
const clientDist=path.join(__dirname,'..','client','dist');
app.get('/api/health',(q,s)=>s.json({ok:true,service:'ipl-auction-wars'}));
const server=http.createServer(app),io=new Server(server,{cors:{origin:'*'}});const rooms=new Map();
function newRoom(){let id=Math.random().toString(36).slice(2,7).toUpperCase();rooms.set(id,{id,users:{},teams:{},players:players.map((p,i)=>({...p,id:i+1})),index:0,current:null,bid:0,bidder:null,timer:null,status:'lobby'});return id}
function publicRoom(r){return {id:r.id,users:Object.values(r.users),teams:r.teams,current:r.current,bid:r.bid,bidder:r.bidder,status:r.status,remaining:r.remaining,playersLeft:r.players.length-r.index}}
function start(r){if(r.status==='auction')return;r.status='auction';next(r)}
function next(r){clearInterval(r.timer);if(r.index>=r.players.length){r.status='finished';io.to(r.id).emit('state',publicRoom(r));return}r.current=r.players[r.index++];r.bid=r.current.base;r.bidder=null;r.remaining=15;r.timer=setInterval(()=>{r.remaining--;io.to(r.id).emit('state',publicRoom(r));if(r.remaining<=0){clearInterval(r.timer);if(r.bidder){let t=r.teams[r.bidder];t.players.push({...r.current,price:r.bid});t.budget-=r.bid}setTimeout(()=>next(r),1200)}},1000);io.to(r.id).emit('state',publicRoom(r))}
io.on('connection',s=>{s.on('create',({name,team},cb)=>{let id=newRoom(),r=rooms.get(id);r.users[s.id]={id:s.id,name,team};r.teams[team]={owner:s.id,name:team,budget:12000,players:[]};s.join(id);cb(id);io.to(id).emit('state',publicRoom(r))});s.on('join',({room,name,team},cb)=>{let r=rooms.get(room);if(!r)return cb({error:'Room not found'});r.users[s.id]={id:s.id,name,team};if(!r.teams[team])r.teams[team]={owner:s.id,name:team,budget:12000,players:[]};s.join(room);cb({ok:true});io.to(room).emit('state',publicRoom(r))});s.on('start',room=>{let r=rooms.get(room);if(r)start(r)});s.on('bid',room=>{let r=rooms.get(room),u=r&&r.users[s.id],t=u&&r.teams[u.team];if(!r||r.status!=='auction'||!r.current||!t||t.budget<r.bid+50)return;if(r.bidder===s.id)return;r.bid+=50;r.bidder=s.id;r.remaining=15;io.to(room).emit('state',publicRoom(r))})});
if(require('fs').existsSync(clientDist)){app.use(express.static(clientDist));app.get('*',(q,s)=>s.sendFile(path.join(clientDist,'index.html')))}
const PORT=process.env.PORT||10000;server.listen(PORT,'0.0.0.0',()=>console.log(`IPL Auction Wars running on ${PORT}`));
